#!/usr/bin/env bash

# Show the screen brightness value given by `xbacklight`.
# Right click toggles dark/light mode using darkman.
# Scrolling increases or decreases the brightness.

STEP_SIZE=${STEP_SIZE:-5}
USE_SUDO=${USE_SUDO:-0}

# whether to use `sudo` for changing the brightness (requires a NOPASSWD rule)
if [[ "$USE_SUDO" == "0" ]] ; then
    XBACKLIGHT_SET="xbacklight"
else
    XBACKLIGHT_SET="sudo xbacklight"
fi

case $BLOCK_BUTTON in
  3) darkman toggle ;; # jobb kattintás: váltás dark/light mód között
  4) $XBACKLIGHT_SET -inc "$STEP_SIZE" ;; # scroll up
  5) $XBACKLIGHT_SET -dec "$STEP_SIZE" ;; # scroll down
esac

BRIGHTNESS=$(xbacklight -get | cut -f1 -d'.')
MODE=$(darkman status)   # lekéri az aktuális témát (dark vagy light)

echo "${BRIGHTNESS}% ($MODE)"
