#!/usr/bin/env perl
#
# i3blocks battery script with toggle details on click
#

use strict;
use warnings;
use utf8;
use POSIX qw(strftime);

my $toggle_file = "/tmp/battery_toggle";

# read toggle state (0 = only icon, 1 = details)
my $show_details = 0;
if (-e $toggle_file) {
    open(my $fh, "<", $toggle_file);
    my $line = <$fh>;
    close($fh);
    chomp($line);
    $show_details = $line if defined $line;
}

# handle click
if ($ENV{BLOCK_BUTTON} && $ENV{BLOCK_BUTTON} == 1) {
    $show_details = $show_details ? 0 : 1;
    open(my $fh, ">", $toggle_file);
    print $fh $show_details;
    close($fh);
}

# battery info
my ($acpi, $status, $percent, $ac_adapt);
my ($full_text, $short_text);
my $bat_number = $ENV{BAT_NUMBER} || 0;

open(my $ACPI, "acpi -b 2>/dev/null | grep 'Battery $bat_number' |") or die;
$acpi = <$ACPI>;
close($ACPI);

if (not defined($acpi)) { exit(0); }
elsif ($acpi !~ /: ([\w\s]+), (\d+)%/) { die "$acpi\n"; }

$status  = $1;
$percent = $2;

my $second = strftime("%S", localtime);

# ikon választás
my $icon;
if ($status eq 'Charging') {
    my @icons = ("", "", "", "");
    $icon = $icons[$second % 4];
} elsif ($status eq 'Discharging') {
    if ($percent < 20) {
        $icon = ($second % 2 == 0) ? "" : " ";
    } elsif ($percent < 40) { $icon = ""; }
    elsif ($percent < 60)   { $icon = ""; }
    elsif ($percent < 85)   { $icon = ""; }
    else                    { $icon = ""; }
} else {
    $icon = "🔋";
}

# alapállapot: csak ikon
$full_text  = $icon;
$short_text = $icon;

# ha részletes mód aktív
if ($show_details) {
    $full_text = "$icon $percent% $status";
    $short_text = "$icon $percent%";
    if ($acpi =~ /(\d\d:\d\d):/) {
        $full_text .= " ($1)";
    }
}

# kiírás
print "$full_text\n";
print "$short_text\n";

# színek
if ($status eq 'Discharging') {
    if    ($percent < 20) { print "#FF0000\n"; }
    elsif ($percent < 40) { print "#FFAE00\n"; }
    elsif ($percent < 60) { print "#FFF600\n"; }
    elsif ($percent < 85) { print "#A8FF00\n"; }
    else                  { print "#00FF00\n"; }
    if ($percent < 5) { exit(33); }
} elsif ($status eq 'Charging') {
    print "#00FF00\n";
}

exit(0);
