#!/usr/bin/env bash

# Interface autodetect
IF="${IFACE:-$BLOCK_INSTANCE}"
IF="${IF:-$(ip route | awk '/^default/ { print $5 ; exit }')}"
[[ -z "$IF" ]] && exit
[[ ! -d /sys/class/net/${IF} ]] && exit

AF=${ADDRESS_FAMILY:-inet}
LABEL="${LABEL:-}"

# IP lekérés
IPADDR=$(ip addr show $IF | perl -n -e "/$AF ([^ \/]+).* scope global/ && print \$1 and exit")

# Állapotfájl toggle-hoz
STATEFILE="/tmp/i3blocks_net_toggle"

# Ha nincs kapcsolat → piros ikon
if [[ "$IF" = "" ]] || [[ "$(cat /sys/class/net/$IF/operstate)" = 'down' ]]; then
  echo "❌"        # full text
  echo "❌"        # short text
  echo "#FF0000"   # color
  exit
fi

# Bal kattintás → toggle állapot
if [[ $BLOCK_BUTTON -eq 1 ]]; then
  if [[ -f "$STATEFILE" ]]; then
    rm "$STATEFILE"   # vissza ikon módba
  else
    touch "$STATEFILE" # IP módba
  fi
fi

# Jobb kattintás → IP vágólapra
if [[ $BLOCK_BUTTON -eq 3 ]]; then
  echo -n "$IPADDR" | xclip -q -se c
fi

# Megjelenítés logika
if [[ -f "$STATEFILE" ]]; then
  # IP mód
  if command -v iw > /dev/null && iw $IF info > /dev/null 2>&1; then
    WIFI_NAME=$(iw $IF info | grep -Po '(?<=ssid ).*' | tr -d " \t\n\r")
    echo "󰈀 $WIFI_NAME ($IPADDR)"
  else
    echo "󰈀 $IPADDR"
  fi
else
  # Ikon mód
  echo "󰈀"
fi
