#!/usr/bin/env perl
use strict;
use warnings;
use POSIX qw/strftime/;

my $click   = $ENV{BLOCK_BUTTON} || 0;
my $state_file = "$ENV{HOME}/.clock_state";

# formátumok
my $simple_format = "%H:%M";
my $detail_format = "%Y-%m-%d %H:%M %Z";

# állapot beolvasása
my $show_details = 0;
if (-f $state_file) {
    open my $fh, '<', $state_file or die "Couldn't open $state_file";
    my $line = <$fh>;
    chomp $line;
    $show_details = $line eq "1" ? 1 : 0;
    close $fh;
}

# kattintás esetén váltás
if ($click == 1) {
    $show_details = !$show_details;
    open my $fh, '>', $state_file or die "Couldn't write $state_file";
    print $fh $show_details ? "1\n" : "0\n";
    close $fh;
}

# kiírás mindig 3 sorban
binmode(STDOUT, ":utf8");
my $format = $show_details ? $detail_format : $simple_format;
my $time = strftime($format, localtime());

print "$time\n";       # full_text
print "$time\n";       # short_text (ugyanaz most)
print "FFFFFF";            # color (üres)
