#!/usr/bin/env bash
# Wifi block for i3blocks
# Toggle details with left click

if [[ -z "$INTERFACE" ]] ; then
    INTERFACE="${BLOCK_INSTANCE:-wlan0}"
fi

STATE_FILE="/tmp/i3blocks_wifi_state"

COLOR_GE80=${COLOR_GE80:-#80dfff}
COLOR_GE60=${COLOR_GE60:-#FFF600}
COLOR_GE40=${COLOR_GE40:-#FFAE00}
COLOR_LOWR=${COLOR_LOWR:-#FF0000}
COLOR_DOWN=${COLOR_DOWN:-#FF0000}

[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] && exit

if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
    echo "down"
    echo "down"
    echo $COLOR_DOWN
    exit
fi

SSID=$(iw dev ${INTERFACE} link | grep 'SSID' | awk '{print $2}')
QUALITY=$(iw dev ${INTERFACE} link | grep 'dBm$' | grep -Eoe '-[0-9]{2}' | \
    awk '{print  ($1 > -50 ? 100 :($1 < -100 ? 0 : ($1+100)*2))}')
IP=$(ip addr show ${INTERFACE} | grep 'inet ' | awk '{print $2}' | cut -d/ -f1)

# Toggle state on left click
if [[ "$BLOCK_BUTTON" == "1" ]]; then
    if [[ -f "$STATE_FILE" ]]; then
        rm "$STATE_FILE"   # ha létezik, töröljük → visszazárás
    else
        touch "$STATE_FILE" # ha nincs, létrehozzuk → kinyitás
    fi
fi

# Megjelenítés az állapot alapján
if [[ -f "$STATE_FILE" ]]; then
    FULL_TEXT="󰖩 $SSID | Signal: $QUALITY% | IP: $IP"
else
    FULL_TEXT="󰖩 $SSID"
fi

echo "$FULL_TEXT"
echo "$FULL_TEXT"

if [[ $QUALITY -ge 80 ]]; then
    echo $COLOR_GE80
elif [[ $QUALITY -ge 60 ]]; then
    echo $COLOR_GE60
elif [[ $QUALITY -ge 40 ]]; then
    echo $COLOR_GE40
else
    echo $COLOR_LOWR
fi
